config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :albums do
    resources :photos, only: [:show,:new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
  end

  root to: 'albums#index'
  resources :users, only: [:show]
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, presence: true
  validates :image, presence: true
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: false
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :images
  belongs_to :album
  belongs_to :user
  has_many :comments, dependent: :destroy

  before_validation :set_posted_date

  validates :posted_date, presence: true
  validates :images, presence: true

  private
  
  def was_attached?
    self.image.attached?
  end

  def set_posted_date
    self.posted_date = Date.today if self.posted_date.nil? 
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
  has_many :comments
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]
  before_action :set_album, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  def index
    @albums = Album.includes(:user)
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to @album
    else
      render :new
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to "/users/#{current_user.id}"
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to @album
    else
      render :edit
    end
  end

  def show
    @photos = @album.photos
    @nickname = current_user.nickname
  end

  private

  def album_params
    params.require(:album).permit(:title, :image).merge(user_id: current_user.id)
  end

  def set_album
    @album = Album.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def authorize_user!
    unless @album.user == current_user
      redirect_to new_user_session_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)  
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_comment, only: [:destroy]
  
  def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:photo_id])
    @comment = @photo.comments.build(comment_params)
    
    if current_user.nil? 
      flash[:alert] = "ログインしてください。" 
      redirect_to new_user_session_path 
      return 
    end

    @comment.user = current_user

    if @comment.save
      redirect_to album_path(@album)
    else
      render 'photos/show'
    end
  end

  def destroy
    if @comment.user == current_user 
      @comment.destroy
      redirect_to album_path(@comment.photo.album)
    else
      flash[:alert] = 'コメントの削除権限がありません。'
      redirect_to album_path(@comment.photo.album)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_album, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @photo = @album.photos.new
  end

  def create
    @photo = @album.photos.new(photo_params.except(:image))
    @photo.user = current_user

    if @photo.save
      images = Array.wrap(photo_params[:image]).reject(&:blank?)
      images.each do |image|
        @photo.image.attach(image)
      end

      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if  @photo.update(photo_params.except(:image))
        images = Array.wrap(photo_params[:image]).reject(&:blank?)
        @photo.image.purge_later if photo_params[:image].present?
        images.each do |image|
          @photo.image.attach(image)
        end

      redirect_to album_path(@album)
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to album_path(@album)
  end

  def show
    @comment = @photo.comments.build
  end

  private

  def set_album
    @album = Album.find(params[:album_id])
  end

  def set_photo
    @photo = @album.photos.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:description, :images)
  end

  def authorize_user!
    unless @album.user == current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @albums = current_user.albums
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @album, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "title" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/albums/index.html.erb
<div class="lifestory-contents row">
  <section id="lifestory-intro">
    <div class="lifestory-intro-content">
      <h2>写真と物語が繋ぐ、特別な場所</h2>
    </div>
  </section>

  <section id="lifestory-features">
    <h2>機能紹介</h2>
    <ul class="lifestory-features-list">
      <li class="lifestory-feature-item">
        写真や動画の共有
        <img src="<%= asset_path('AdobeStock_359569550.jpeg') %>" alt="写真や動画の共有">
      </li>
      <li class="lifestory-feature-item">
        アルバム作成機能
        <img src="<%= asset_path('AdobeStock_377689537.jpeg') %>" alt="アルバム作成機能">
      </li>
      <li class="lifestory-feature-item">
        プライバシー設定
        <img src="<%= asset_path('AdobeStock_215178828.jpeg') %>" alt="プライバシー設定">
      </li>
      <li class="lifestory-feature-item">
        家族との共同編集
        <img src="<%= asset_path('AdobeStock_250192845.jpeg') %>" alt="フレンドとの共同編集">
      </li>
      <li class="lifestory-feature-item">
        スライドショーの再生機能
        <img src="<%= asset_path('AdobeStock_536583422.jpeg') %>" alt="スライドショーの再生機能">
      </li>
    </ul>
  </section>

  <section id="lifestory-banner" class="banner-section">
  <div class="banner-text">
    <h2>製作者の想い</h2>
    <p></p>
  </div>
</section>

  <section id="lifestory-thoughts" class="thoughts-section">
  <div class="thoughts-content">
    <div class="text-content">
      <p>
        家族や友人との大切な瞬間を一生の宝物として残したい。離れていても笑顔や感動を共有したい。思い出を振り返るたびに幸せな気持ちになれるように、私たちのアプリは誕生しました。一瞬一瞬が宝物であり、その瞬間を逃さず美しく保存することで、未来の自分や家族に愛と感動を伝え続けたい。安心して使えるプライバシー管理と簡単な操作で、誰もがいつでも思い出を共有できる場所を提供します。心からの情熱を込めて、このアプリを作りました。
      </p>
    </div>
    <div class="image-content">
      <img src="<%= asset_path('AdobeStock_261487920.jpeg') %>" alt="バナー画像">
    </div>
  </div>
</section>

<section id="lifestory-testimonials">
  <div class="contents row albums-page">
    <h2>アルバム例</h2>
    <p>鈴木さんのアルバム例</p>
    <div class="albums">
      <!--1つ目のアルバム-->
      <div class="album">
        <div class="more">
          <span><h2 class="album-title">ゆうきくん</h2></span>
        </div>
        <div class="album-images">
          <!-- 固定画像1 -->
          <%= image_tag "AdobeStock_167647019.jpeg", class: "album-photo" %>
        </div>
      </div>
      <!--2つ目のアルバム-->
      <div class="album">
        <div class="more">
          <span><h2 class="album-title">家族の集い</h2></span>
        </div>
        <div class="album-images">
          <!-- 固定画像2 -->
          <%= image_tag "AdobeStock_481488260.jpeg", class: "album-photo" %>
        </div>
      </div>
    </div>
  </div>
</section>

  <section id="lifestory-download">
    <h2>ダウンロード</h2>
    <a href="https://www.apple.com/jp/ios/app-store/">App Store</a>
    <a href="https://play.google.com/store">Google Play</a>
  </section>

  <section id="lifestory-contact">
    <h2>お問い合わせ</h2>
    <form action="/contact" method="post">
      <input type="text" name="name" placeholder="名前">
      <input type="email" name="email" placeholder="メールアドレス">
      <textarea name="message" placeholder="メッセージ"></textarea>
      <button type="submit">送信</button>
    </form>
  </section>
</div>

app/views/albums/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>アルバム作成</h3>
    <%= form_with(model: @album, local: true) do |form| %>
      <%= form.label "アルバム名" %>
      <%= form.text_field :title %>

      <%= form.label "アルバム写真" %>
      <%= form.file_field :image %>
      <%= form.submit "作成する" %>
    <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<div class="contents row photo-page">
  <% if @photos.any? %>
    <p><%= @album.title %>の写真一覧(<span id="photo-count"><%= @photos.size %></span>件)</p>
    <div class="albums">
      <% @photos.each do |photo| %>
        <div class="album">
          <div class="more">
            <p class="album-title">・・・</p>
            <ul class="more_list">
              <li>
                <%= link_to '編集', edit_album_photo_path(@album, photo) %>
              </li>
              <li>
                <%= link_to '削除', album_photo_path(@album, photo), data: { turbo_method: :delete } %>
              </li>
            </ul>
          </div>
          <% if photo.images.attached? %>
            <%= link_to album_photo_path(@album, photo) do %>
              <%= image_tag photo.images, class: "album-photo" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>このアルバムにはまだ写真がありません</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeStory41802</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <% if params[:controller] == 'albums' && params[:action] == 'index' %>
      <%= stylesheet_link_tag 'application', 'responsive', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">LifeStory</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
          </span>
          <% if params[:controller] == 'users' && params[:action] == 'show' && params[:id].to_i == current_user.id %>
            <%= link_to "作成する", new_album_path, class: "post" %>
          <% end %>
          <% if params[:controller] == 'albums' && params[:action] == 'show' && @album.present? %>
            <%= link_to "写真追加", new_album_photo_path(@album), class: "post" %>
          <% end %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright  LifeStory41802
      </p>
    </footer>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: [@album, @photo], local: true) do |form| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% @photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "メモ" %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>メモを編集する</h3>
    <%= render 'form', album: @album, photo: @photo %>
    <%= link_to '戻る', album_path(@album) %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>新しい写真を追加する</h3>
    <%= form_with(model: [@album, @photo], local: true, html: { class: 'photo-form', multipart: true }) do |form| %>
      <div class="field">
        <%= form.label :description, "メモ" %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="field">
    <%= form.label :images, "写真" %>
    <%= form.file_field :images , id:"posts_image" %>
  </div>

      <div class="actions">
        <%= form.submit "追加する", class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to '戻る', album_path(@album), class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="contents row photo-page">
  <div class="photo-page-album">
    <p class="photo-page-album-title"><%= @album.title %></p>
    <div class="photo-page-more">
      <p class="album-title">・・・</p>
      <ul class="photo-page-more-list">
        <li>
          <%= link_to '編集', edit_album_photo_path(@album, @photo) %>
        </li>
        <li>
          <%= link_to '削除', album_photo_path(@album, @photo), data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>

    <% if @photo.images.attached? %>
      <div class="photo-page-album-image-wrapper">
        <%= image_tag @photo.images, class: "photo-page-album-photo" %>
      </div>
    <% else %>
      <p>写真が表示されません。</p>
    <% end %>

    <div class="photo-page-description">
      <h4>写真メモ</h4>
      <p><%= @photo.description %></p>

      <h4>コメント</h4>
      <div class="comment">
        <% @photo.comments.each do |comment| %>
          <div class="comment-header">
            <% if comment.user %>
              <span class="comment-user-name"><%= comment.user.nickname %></span>
            <% end %>
            <span class="comment-timestamp"><%= comment.created_at %></span>
            <% if comment.user == current_user %>
              <%= link_to "削除", album_photo_comment_path(@album, @photo, comment), data: { turbo_method: :delete }, class: "comment-delete-link" %>
            <% end %>
          </div>
          <p><%= comment.content %></p>
        <% end %>

        <%= form_with(model: @comment, url: album_photo_comments_path(@album, @photo), local: true) do |form| %>
          <div class="form-group">
            <%= form.text_area :content, class: 'form-control', style: 'resize: none;', placeholder: 'コメントを入力してください' %>
          </div>
          <%= form.submit 'コメントを追加', class: 'btn btn-primary' %>
        <% end %>
      </div>

      <%= link_to '戻る', album_path(@album), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row albums-page">
  <p><%= @nickname %>さんのアルバム一覧</p>
  <div class="albums">
    <% @albums.each do |album| %>
      <div class="album">
        <div class="more">
          <span><h2 class="album-title"><%= album.title %></h2></span>
          <ul class="more_list">
            <li>
              <%= link_to '編集', edit_album_path(album) %>
            </li>
            <li>
              <%= link_to '削除', album_path(album), data: { turbo_method: :delete } %>
            </li>
          </ul>
        </div>
        <% album.image.each do |image| %>
          <%= link_to album_path(album) do %>
            <%= image_tag image, class: "album-photo" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>